apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: torus9x-nest-app-backend-container
        image: 192.168.2.164:5000/torus9x-nest-app:${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent 
        ports:
        - name: http
          containerPort: 3002
        env:
        - name: redis_host  # Corrected key name from "redis host" to "redis_host"
          value: "192.168.2.165"
        - name: redis_port  # Corrected key name from "redis port" to "redis_port"
          value: "8085"
        livenessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 30   # Adjust the initial delay here
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3002
    nodePort: 30002
  selector:
    app: nestjs-app
