apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
  labels:
    app: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: torus9x-nest-app-backend-container
        image: 192.168.2.164:5000/torus9x-nest-app:${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3002  # Fixed indentation and added missing 'containerPort' key
        env:
        - name: redis_host
          value: 192.168.2.165  # Ensure value is quoted if needed
        - name: redis_port
          value: 8085  # Ensure value is quoted if needed
        livenessProbe:
          httpGet:
            path: /  # Correct path for livenessProbe
            port: http  # Use the port name defined in 'ports' section
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /  # Correct path for readinessProbe
            port: http  # Use the port name defined in 'ports' section
          initialDelaySeconds: 30
