apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nest-app-backend-container
        image: 192.168.2.164:5000/torus9x-nest-app:${IMAGE_TAG}
        ports:
        - containerPort: 3002
        env:
        - name: redis_host  # Corrected to use underscore instead of space
          value: "192.168.2.165"
        - name: redis_port  # Corrected to use underscore instead of space
          value: "8085"
