apiVersion: v1
kind: Service
metadata:
  name: nestjs-app
  namespace: nestjs
  labels:
    app: nestjs-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3002
    nodePort: 30002
  selector:
    app: nestjs-app
